---
site_name: Learn Ragdoll
site_description: The real-time physics solver for Maya
site_author: mottosso
site_url: https://learn.ragdolldynamics.com

# Repository
repo_name: mottosso/ragdoll
repo_url: https://github.com/mottosso/ragdoll
edit_uri: edit/main/docs/pages

copyright: "Copyright &copy; 2020-2021 mottosso"

# Page tree
nav:
  - Home: index.md
  - Overview: overview.md
  - Documentation:
    - Marker: documentation/marker.md
    - Group: documentation/group.md
    - Solver: documentation/solver.md
    - Manipulator: documentation/manipulator.md
    - Constraints: documentation/constraints.md
    - Record Simulation: documentation/record_simulation.md
    - Snap to Simulation: documentation/snap_to_simulation.md
    - Retargeting: documentation/retargeting.md
    - Cache: documentation/cache.md
    - Link: documentation/link.md
    - Utilities: documentation/utilities.md
  - Tutorials:
    - Videos: tutorials/videos.md
    - Manikin: tutorials/manikin.md
    - Full Ragdoll: tutorials/manikin_ragdoll.md
    - IK: tutorials/manikin_ik.md
    - Mocap Chap: tutorials/mocap_chap.md
  - Download: download.md
  - Examples: examples.md
  - Menu Reference: menu.md
  - Node Reference: nodes.md
  - API Reference: api.md
  - Release History:  # Automatically generated
    - 2021.07.15: releases/2021.07.15.md
  - Licencing: licencing.md
  - Serialisation: serialisation.md
  - About: about.md
  - Legacy:
    - Active Rigid: documentation/active_rigid.md
    - Active Chain: documentation/active_chain.md
    - Active Character: documentation/character.md
    - Constraints: documentation/old_constraints.md
    - Soft Pin: documentation/soft_pin.md
    - Hard Pin: documentation/hard_pin.md
    - Mimic: documentation/mimic.md
    - Forces: documentation/forces.md
    - Bake Simulation: documentation/bake_simulation.md
    - Import Physics: documentation/import_physics.md
    - Export Physics: documentation/export_physics.md
    - Scene Management: documentation/scene_management.md
    - Cycle Protection: documentation/cycle_protection.md
    - Pivot Editor: documentation/pivot_editor.md
    - Debugging Tips: documentation/debugging_tips.md
    - Performance Tips: documentation/performance_tips.md
    - Tutorials:
      - Bouncing Ball: tutorials/bouncing_ball.md
      - Rally Car: tutorials/rally_car.md
      - Manikin: tutorials/old_manikin.md

icons:
  - Active Rigid: icons/rigid.png

docs_dir: pages

theme:
  name: material
  logo: ragdoll_full.png
  logo: ragdoll_silhouette_black_512.png
  favicon: favicon-256x256.png
  custom_dir: theme
  palette:
    primary: "white"
    accent: "white"

extra_css:
  - extra.css
  # Landing page includes additional CSS from landing.html

# Options
extra:
  feature:
    tabs: true

extra_javascript:
  - "extra.js"

markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: monokai
  - extra
  - admonition
  - def_list
  - footnotes
  - meta
  - toc
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date
  - mkdocs-ragdoll
